"""empty message

Revision ID: 4b247a98e92a
Revises: 959ddf254951
Create Date: 2024-03-06 10:37:29.992563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b247a98e92a'
down_revision = '959ddf254951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('situacao', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoque', schema=None) as batch_op:
        batch_op.drop_column('situacao')

    # ### end Alembic commands ###
