"""empty message

Revision ID: 68360ccea408
Revises: c777dbf78b9d
Create Date: 2024-02-27 19:59:09.322679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68360ccea408'
down_revision = 'c777dbf78b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtarefa', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('especie', sa.Integer(), nullable=True))
        batch_op.drop_column('matricula')
        batch_op.drop_column('solicitante')
        batch_op.drop_column('tipo')
        batch_op.drop_column('dt_solicitacao')
        batch_op.drop_column('unidade')
        batch_op.drop_column('protocolo')
        batch_op.drop_column('dt_conclusao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dt_conclusao', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('protocolo', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('unidade', mysql.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('dt_solicitacao', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('tipo', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('solicitante', mysql.VARCHAR(length=7), nullable=False))
        batch_op.add_column(sa.Column('matricula', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('especie')
        batch_op.drop_column('subtarefa')

    # ### end Alembic commands ###
