"""empty message

Revision ID: 705908f3e0c5
Revises: bfa4274c41d2
Create Date: 2024-01-18 18:33:12.816796

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '705908f3e0c5'
down_revision = 'bfa4274c41d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solicitante', sa.String(length=7), nullable=False))
        batch_op.drop_column('solicitate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solicitate', mysql.VARCHAR(length=7), nullable=False))
        batch_op.drop_column('solicitante')

    # ### end Alembic commands ###
