"""empty message

Revision ID: ac24c29d58fb
Revises: d6d585237ffb
Create Date: 2024-01-18 16:16:04.160505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac24c29d58fb'
down_revision = 'd6d585237ffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dt_solicitacao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('dt_conclusao', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.drop_column('dt_conclusao')
        batch_op.drop_column('dt_solicitacao')

    # ### end Alembic commands ###
