"""empty message

Revision ID: bfa4274c41d2
Revises: ac24c29d58fb
Create Date: 2024-01-18 18:24:45.171568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bfa4274c41d2'
down_revision = 'ac24c29d58fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solicitate', sa.String(length=7), nullable=False))
        batch_op.alter_column('unidade',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('unidade',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('solicitate')

    # ### end Alembic commands ###
