"""empty message

Revision ID: ed3578034221
Revises: c4729cd50432
Create Date: 2024-01-18 12:31:07.930450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed3578034221'
down_revision = 'c4729cd50432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.alter_column('matricula',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('unidade',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('unidade',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('matricula',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
